import Head from 'next/head';
// import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Qr Labs</h1>

        <div>
          <a href="/scan">
            <h2>Scan a qr code&rarr;</h2>
            <p>Scan a qr code with your camera</p>
          </a>

          <a href="/generate">
            <h2> Generate a qr code&rarr;</h2>
            <p> Generate a qr code with text or a link</p>
          </a>
        </div>
      </main>
    </div>
  );
}
